### PR TITLE
Component Testing Best Practices for VFS Apps

### PR DESCRIPTION
**Pull request by alexandec**
## RFC Preview Link
https://github.com/department-of-veterans-affairs/va.gov-platform-architecture/blob/component-testing-best-practices/rfc/2022/2022-10-26_Component%20Testing%20Best%20Practices%20for%20VFS%20Apps.md

## Comment Period End Date
2022-11-16

### CODE REVIEW

**Review by mchelen-gov — APPROVED** [review]

**Comment by mchelen-gov** [comment]
@alexandec approved 👍

**Comment by alexandec** [comment]
@mchelen-gov thanks! Looks like I'm not allowed to merge it myself, is that something you would do?

**Comment by mchelen-gov** [comment]
> @mchelen-gov thanks! Looks like I'm not allowed to merge it myself, is that something you would do?

Hmm interesting, this might be a permissions issue that we need to fix.

**Comment by alexandec** [comment]
Looks like Clint was able to merge it so we're good. But if you want the PR creator to be able to merge, we'll have to modify the repo settings.

**Pull request merged**
